Repository SPbSTU-OPD-Palihindron-team/Open-space-map-constructor-BackEnd, pull requests merged in 2022-05, with the labels that each got.

#24 Generation code for DB entity from Postgres to Hibernate lib enhancement
  pom.xml
  src/main/java/org/openspace_map/AccessibilityType.java
  src/main/java/org/openspace_map/Building.java
  src/main/java/org/openspace_map/BuildingFloor.java
  src/main/java/org/openspace_map/Employee.java
  src/main/java/org/openspace_map/FloorType.java
  src/main/java/org/openspace_map/FloorZone.java
  src/main/java/org/openspace_map/Item.java
  src/main/java/org/openspace_map/ItemType.java
  src/main/java/org/openspace_map/PlacementType.java
  src/main/java/org/openspace_map/RegisteredUsers.java
  src/main/java/org/openspace_map/Wall.java
  src/main/java/org/openspace_map/WallType.java
  src/main/java/org/openspace_map/WorkplaceItem.java
  src/main/java/org/openspace_map/WorkplaceItemEmployeeRelation.java
  src/main/resources/application.properties
Labels: enhancement

#30 Issue 28-29 Fix Database
  documents/open_space_map_constructor_database.png
  documents/src/open_space_map_constructor_database.uxf
  pom.xml
  queries/map_database_initialization.sql
  space_map_compose.yml
  src/main/java/org/openspace_map/AccessibilityType.java
  src/main/java/org/openspace_map/Building.java
  src/main/java/org/openspace_map/BuildingFloor.java
  src/main/java/org/openspace_map/Employee.java
  src/main/java/org/openspace_map/FloorType.java
  src/main/java/org/openspace_map/FloorZone.java
  src/main/java/org/openspace_map/Item.java
  src/main/java/org/openspace_map/ItemType.java
  src/main/java/org/openspace_map/PlacementType.java
  src/main/java/org/openspace_map/RegisteredUser.java
  src/main/java/org/openspace_map/RegisteredUsers.java
  src/main/java/org/openspace_map/Wall.java
  src/main/java/org/openspace_map/WallType.java
  src/main/java/org/openspace_map/WorkplaceItem.java
  src/main/java/org/openspace_map/WorkplaceItemEmployeeRelation.java
  src/main/resources/application.properties
Labels: bug, enhancement

#33 Issue 27 implement items rest api paths
  map_docker_run.sh
  map_podman_run.sh
  space_map_compose.yml
  src/main/java/org/openspace_map/Item.java
  src/main/java/org/openspace_map/ItemService.java
  src/main/java/org/openspace_map/ItemsService.java
  src/main/java/org/openspace_map/ItemsTypesService.java
  src/main/resources/api.yaml
Labels: documentation, enhancement
